name: swiftformat

on:
  push:
    branches: ["**"]
    paths: ["**.swift"]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/setup-mint@v1

      - run: bin/format

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: format
